#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          6

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Blueman-manager desktop='^10'
bspc rule -a Pavucontrol desktop='^10'
bspc rule -a discord desktop='^1' follow=on
{{ if ne .chezmoi.config.data.has_package_firefox-esr true -}}
bspc rule -a firefox-esr --one-shot  desktop='^2'
{{ else }}
bspc rule -a firefox --one-shot  desktop='^2'
{{ end }}
bspc rule -a Code --one-shot  desktop='^3'
bspc rule -a easyeffects desktop='^9'
bspc rule -a Spotify desktop='^8'

export PATH="${PATH}:$HOME/.local/bin"

#$HOME/.config/scripts/jankvisor/launch_bt.sh &
pavucontrol &
discord &
firefox &
code &
spotify-launcher &
easyeffects &
$HOME/.config/scripts/wallpaper/initwallpaper.sh &
polybar mybar 2>&1 &
dunst &
xset -dpms &
xset s off &
